# Generated by Django 5.1 on 2024-08-31 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readit', '0006_board_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='readit.board'),
            preserve_default=False,
        ),
    ]
